//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrabble2018.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class skin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal skin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrabble2018.Locales.skin", typeof(skin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hewlett-Packard.
        /// </summary>
        internal static string AssemblyInfo_AssemblyCompany {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssemblyInfo_AssemblyConfiguration {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Hewlett-Packard 2018.
        /// </summary>
        internal static string AssemblyInfo_AssemblyCopyright {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssemblyInfo_AssemblyCulture {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssemblyInfo_AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string AssemblyInfo_AssemblyFileVersion {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrabble.
        /// </summary>
        internal static string AssemblyInfo_AssemblyProduct {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrabble.
        /// </summary>
        internal static string AssemblyInfo_AssemblyTitle {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssemblyInfo_AssemblyTrademark {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyTrademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string AssemblyInfo_AssemblyVersion {
            get {
                return ResourceManager.GetString("AssemblyInfo.AssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass.
        /// </summary>
        internal static string GameState_LastAction_Pass {
            get {
                return ResourceManager.GetString("GameState.LastAction.Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        internal static string GameState_LastAction_Play {
            get {
                return ResourceManager.GetString("GameState.LastAction.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap.
        /// </summary>
        internal static string GameState_LastAction_Swap {
            get {
                return ResourceManager.GetString("GameState.LastAction.Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players: {0}.
        /// </summary>
        internal static string Model_NumofPlayers {
            get {
                return ResourceManager.GetString("Model.NumofPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome players! Welcome to Scrabble!.
        /// </summary>
        internal static string Model_WelcomePlayers {
            get {
                return ResourceManager.GetString("Model.WelcomePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Comparison Exception.
        /// </summary>
        internal static string Player_PlayerException {
            get {
                return ResourceManager.GetString("Player.PlayerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} scored {1} points now!.
        /// </summary>
        internal static string Player_PlayerScore {
            get {
                return ResourceManager.GetString("Player.PlayerScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles Comparison Exception.
        /// </summary>
        internal static string Tile_Tles_TileException {
            get {
                return ResourceManager.GetString("Tile.Tles.TileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First up is player {0}.
        /// </summary>
        internal static string View_DesktopWindow_FirstPlayer {
            get {
                return ResourceManager.GetString("View.DesktopWindow.FirstPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Judge: You didn&apos;t score. Please try again!.
        /// </summary>
        internal static string View_DesktopWindow_GameJudgeScore {
            get {
                return ResourceManager.GetString("View.DesktopWindow.GameJudgeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game starts....
        /// </summary>
        internal static string View_DesktopWindow_GameStart {
            get {
                return ResourceManager.GetString("View.DesktopWindow.GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of players: {0}.
        /// </summary>
        internal static string View_DesktopWindow_NumofPlayers {
            get {
                return ResourceManager.GetString("View.DesktopWindow.NumofPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player decides to pass the turn! Player {0}.
        /// </summary>
        internal static string View_DesktopWindow_PlayerPass {
            get {
                return ResourceManager.GetString("View.DesktopWindow.PlayerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words created by Player {0}:.
        /// </summary>
        internal static string View_DesktopWindow_PlayerWord {
            get {
                return ResourceManager.GetString("View.DesktopWindow.PlayerWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} scores).
        /// </summary>
        internal static string View_DesktopWindow_Scores {
            get {
                return ResourceManager.GetString("View.DesktopWindow.Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t swap tiles now becuase less than 7 tiles are left in the bag!.
        /// </summary>
        internal static string View_DesktopWindow_SwapButton_CannotSwap {
            get {
                return ResourceManager.GetString("View.DesktopWindow.SwapButton.CannotSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tiles you don&apos;t want...Then press the FINISH button..
        /// </summary>
        internal static string View_DesktopWindow_SwapButton_CanSwap {
            get {
                return ResourceManager.GetString("View.DesktopWindow.SwapButton.CanSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        internal static string View_DesktopWindow_SwapButton_Content_Finish {
            get {
                return ResourceManager.GetString("View.DesktopWindow.SwapButton.Content.Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAP.
        /// </summary>
        internal static string View_DesktopWindow_SwapButton_Content_Swap {
            get {
                return ResourceManager.GetString("View.DesktopWindow.SwapButton.Content.Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is finishing swapping tiles! Player {0}.
        /// </summary>
        internal static string View_DesktopWindow_SwapButton_FinishSwapping {
            get {
                return ResourceManager.GetString("View.DesktopWindow.SwapButton.FinishSwapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} gets {1}!.
        /// </summary>
        internal static string View_DesktopWindow_TileDraw {
            get {
                return ResourceManager.GetString("View.DesktopWindow.TileDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} - ScrabbleDesktop.
        /// </summary>
        internal static string View_DesktopWindow_Title {
            get {
                return ResourceManager.GetString("View.DesktopWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn: Player {0}.
        /// </summary>
        internal static string View_DesktopWindow_UpdatePlayerInfoTurn {
            get {
                return ResourceManager.GetString("View.DesktopWindow.UpdatePlayerInfoTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your turn!.
        /// </summary>
        internal static string View_DesktopWindow_YourTurn {
            get {
                return ResourceManager.GetString("View.DesktopWindow.YourTurn", resourceCulture);
            }
        }
    }
}
